server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/mall-learning?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "0926"

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
#    - classpath*:com/**/mapper/*.xml
  type-aliases-package: com.nudt.demo_01.mbg.model

logging:
  file:
    name: D:\workspace\logs\demo_01.log
  level:
    root: info